//
//  MainPresenter.swift
//  MLNumb
//
//  Created by Achmad Jeihan Pahlevi on 10/23/17.
//  Copyright (c) 2017 Achmad Jeihan Pahlevi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
}

class MainPresenter: MainPresentationLogic {
    weak var viewController: MainDisplayLogic?
}
