//
//  imageViewController.swift
//  MLNumb
//
//  Created by Achmad Jeihan Pahlevi on 10/24/17.
//  Copyright (c) 2017 Achmad Jeihan Pahlevi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol imageDisplayLogic: class {
    func display(_ image: UIImage)
    func display(_ prediction: String)
}

class imageViewController: UIViewController, imageDisplayLogic {
    var interactor: imageBusinessLogic?
    var image: UIImage!
    
    @IBOutlet weak var predictionLabel: UILabel!
    @IBOutlet weak var imageView: UIImageView!
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = imageInteractor()
        let presenter = imagePresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    override func viewDidLoad() {
        interactor?.predict(image)
    }
    
    func display(_ image: UIImage) {
        imageView.image = image
    }
    
    func display(_ prediction: String) {
        predictionLabel.text = prediction
    }
}
