//
//  imagePresenter.swift
//  MLNumb
//
//  Created by Achmad Jeihan Pahlevi on 10/24/17.
//  Copyright (c) 2017 Achmad Jeihan Pahlevi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol imagePresentationLogic {
    func present(_ image: UIImage, withPrediction prediction: String)
}

class imagePresenter: imagePresentationLogic {
    weak var viewController: imageDisplayLogic?
    
    func present(_ image: UIImage, withPrediction prediction: String) {
        viewController?.display(image)
        viewController?.display(prediction)
    }
}
